### PR TITLE
UI improvements

### PR DESCRIPTION
**Pull request by sidevesh**
Remove MacOS specific App
Add better and matching systray menu options as NearDrop
Make a better UI for Settings with animations matching the official Windows app
Use hostname for linux as that is the more standard machine name than the distro name
Use libadwaita theme for linux

I removed the MacOS specific App widget because it simplified things and given NearDrop covers MacOS I thought it won't be needed,
in that case we can probably also remove the macos platform director from the source.
if its needed though then I can bring it back and update the PR.

Another issue with the current state of things is that I was not able to get the window to be non resizable with a custom size specified (the small size as shown in the video below),
nor was the always on top call working,
looks like these calls of window_manager aren't working correctly.

Video recording of the UI on Linux:

https://github.com/PlutoHDDev/CrossDrop/assets/17254413/6a6c4013-5d43-47ed-8c34-9615c108b4ed

### CODE REVIEW

**Comment by Medformatik** [comment]
Thank you very much for your contribution, the UI looks perfect! I would be happy if you would modify the PR so that both macOS and Windows are still supported. Windows is absolutely not the focus, but in general my goal is that this app can really be used on all platforms. One app that works and is trusted, not many different ones. Also, I want to have the option to continue replicating Nearby Share beyond the features of NearDrop, so macOS should work then too. As an aside, macOS is my main OS for coding...

**Comment by sidevesh** [comment]
Hey @PlutoHDDev , glad you like it, since you are okay with the direction I took with the UI I will refine things and bring back MacOS support,
just let me know once the Nearby Share functionality starts working, wish I could help you with that but the protobuf stuff is a bit too thick for me to get into right now,
I will help you out on the UI front once we get the functionality working.

**Comment by Medformatik** [comment]
@sidevesh Thank you very much for your interest in supporting this project. I'll let you know once the Nearby Share functionality starts working.
One issue I have noticed is that you are using `async` in `initState`. That won't work, you'll have to find a different solution for that. This might help: https://stackoverflow.com/questions/51901002/is-there-a-way-to-load-async-data-on-initstate-method

**Comment by sidevesh** [comment]
@PlutoHDDev https://github.com/grishka/NearDrop/issues/4#issuecomment-1713326948 NearDrop has receiving files figured out but has issues getting the BLE advertising stuff to work on Mac OS (and iOS) due to lack of APIs.

**Comment by Medformatik** [comment]
@sidevesh I am keeping an eye on NearDrop and the developments regarding sending files, but I have not found a solution to the missing APIs yet. Currently I am focussing the implementation to receive files which is hard enough to do for cross-platform.

**Pull request closed without merging**
